### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [Semper-Viventem/MetaRadar#150]
Your app was confirmed to be a [Reproducible Build](https://reproducible-builds.org/) with our [rbtlog](https://codeberg.org/IzzyOnDroid/rbtlog) – until the current version, which we cannot build anymore as you've [switched to JDK-22](https://github.com/Semper-Viventem/MetaRadar/compare/v0.25.3-beta...v0.26.1-beta). That version is not supported by any stable/LTS release (like Debian Bookworm or Ubuntu Jammy) – but to our knowledge only in Trixie, which is not a stable target.

Would it be an option for you to use JDK-21 instead? That we could easily support. Using Trixie might break anytime, as it's still "in flux" and not a stable/LTS release.

Thanks a lot in advance!

**Comment by Semper-Viventem** [comment]
Hey @IzzySoft, nice to see you again. I see there is a build config for each app in the repo. would it be possible to add trixie jdk 22 separately for [MetaRadar](https://codeberg.org/IzzyOnDroid/rbtlog/src/branch/izzy/log/recipes/f.cking.software.yml)? I did it for the [upstream F-Droid data](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15506/diffs) yesterday.

Also, I have a separate build config for FDroid because it requires the internet connection to be disabled by default, maybe we can create a dedicated build variant for your repo?

**Comment by obfusk** [comment]
It is *possible* to use trixie, yes. But trixie is a moving target. It currently has multiple JDK versions (and sid has even more) but it almost certainly will not ship with all of them when it's released. We don't know if OpenJDK 22 will still be there later. And we'd like to avoid having a build recipe that works today but might break any time in the (near) future.

F-Droid only cares that the build works _for them_, _today_. It doesn't matter to them whether _someone else_ can _reproduce_ the results later (good luck reproducing any f-droid build from before their switch from bullseye to bookworm, let alone builds on stretch). But we want people to be able to independently verify our results. And not just today, but also next month or even next year. Which means we really want to avoid using a setup that cannot be easily replicated and could break any time.

Do you need JDK 22 specifically? Is JDK 21 not an option for some reason? Because we could easily accommodate that.

**Comment by IzzySoft** [comment]
I wonder that F-Droid accepted that, as in the past they always insisted that also older builds need to be kept reproducible for potential later rebuilds. Though as Fay just pointed out, that deviated from how they did it as in hindsight you could hardly tell what JDK something was build with or even on what Debian version.

> maybe we can create a dedicated build variant for your repo?

If that would make it easier for you, why not? We'd then just need to know what APK to fetch (by file pattern regex, e.g. `/iod-release/i`).

**Comment by obfusk** [comment]
FYI, the tag for v0.26.1-beta points to commit 42993e29a331f0b29c8545385d33c765ee7f1d84 but the commit embedded in the APK is b8e58ce7e4f5990bcc4736ceba8040f0155b385d so it will fail to be reproducible.

As [Izzy says](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds):

> §1: Always build the APK from exactly the commit your release-tag will point to!

**Comment by IzzySoft** [comment]
@Semper-Viventem so what's the status here? Currently I have to reset the recipe at each update as we cannot build it. If it takes longer until we find a solution, I'd disable the RB recipe and wait for your ping here.

**Comment by obfusk** [comment]
FYI: OpenJDK 21 is an LTS release, 22-24 are not; trixie will likely ship with OpenJDK 21 only. OpenJDK 22-24 have just been proposed to be removed from trixie. F-Droid's recipe will break when that happens (and sid is too unstable to reliably use as ongoing transitions often make packages temporarily uninstallable). This is exactly why we didn't want to use OpenJDK 22 from trixie. Could you use OpenJDK 21 instead of 22?

**Comment by IzzySoft** [comment]
@Semper-Viventem so what are your plans here? Until today, I've reset the run for your app each time, hoping and waiting for some progress here. As outlined multiple times, JDK22 is no option here; the latest stable we can offer is JDK21 as that's the latest LTS.

I'll stop resetting the recipe tomorrow, as I see no way in getting the current release RB – so it will be marked "RB failed" then. Still have hopes we find a solution for the next release :crossed_fingers:

**Comment by Semper-Viventem** [comment]
Hey @IzzySoft , I'll downgrade JDK to 21 LTS this week. Sorry for the late reply.

**Comment by IzzySoft** [comment]
Thanks, that's good news! Won't help the current release though I'm afraid (APK is already distributed for a week now, not a good idea to replace it). So may I suggest I let the current version fail tomorrow, and we "heal" it with the next then? It won't be a "hard fail" (aka "RB failed") anyway, just a concrete-hard (:stuck_out_tongue_winking_eye:) real build fail, so RB status will show "we tried but could not build".

**Comment by 0000FlyBear0000** [comment]
а где робототехника?

**Comment by Semper-Viventem** [comment]
Hey @IzzySoft, I'm sorry for making you wait. I introduced a new way to setup the JDK version for the project. Now it is possible to setup target JDK from environment variable `JAVA_CONFIG_VERSION` during the configuration build stage. Changes are released since [this PR](https://github.com/Semper-Viventem/MetaRadar/pull/154). I think it will require to support that env variable on your side to setup `JAVA_CONFIG_VERSION: 21`, but I'm not sure about the recipes config syntax

**Comment by IzzySoft** [comment]
This is the block from the failed JDK-22 release:

```yaml
  - tag: v0.26.1-beta
    apks:
      - apk_pattern: app-github-release\.apk
        apk_url: https://github.com/Semper-Viventem/MetaRadar/releases/download/$$TAG$$/app-github-release.apk
        build:
          - ./gradlew assembleGithubRelease
          - mv app/build/outputs/apk/github/release/app-github-release-unsigned.apk /outputs/unsigned.apk
        build_home_dir: /build
        build_repo_dir: /build/repo
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages: []
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```

So you see we have `jdk:` for providing the JDK. We can set that to `21` when switching to `image: ubuntu:jammy`. And if you need a variable set then, it would go into `build:` as the very first step then:

```yaml
        build:
          - export JAVA_CONFIG_VERSION=21
          - ./gradlew assembleGithubRelease
          - mv app/build/outputs/apk/github/release/app-github-release-unsigned.apk /outputs/unsigned.apk
```

So yeah, totally doable.
